
services:
  app:
    container_name: app-backend
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m" 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - .:/home/node/app
    environment:
      - TZ=America/Sao_Paulo
      - MONGO_URL=mongodb://root:root@mongo:27017
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    logging:
      driver: "json-file"
      options:
        max-size: "10m" 
    image: mongo:4.4.6
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root